### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by EnigmaCenter** [nurupo/twitch-prime-offer-claimer#1]
I can make 150 twitch prime accounts a hour
Is there a way to support multiple acccounts?

**Comment by nurupo** [comment]
It's a very simple python script, just fork and edit it for your purposes, shouldn't be that hard, as long as you have Twitch cookies for all of your 150 accounts. I don't plan adding such support though, as I have no need for that.

Also, note that the script currently doesn't work because of the addition of the Overwatch offer which has a new button layout, the script simply doesn't know how to deal with it. I'm a bit lazy to update the script to make it work, maybe I will get around to that in a week.

**Comment by nurupo** [comment]
>Also, note that the script currently doesn't work because of the addition of the Overwatch offer which has a new button layout, the script simply doesn't know how to deal with it. I'm a bit lazy to update the script to make it work, maybe I will get around to that in a week.

Fixed it, now it works, until Twitch changes the website design in a way the script doesn't know how to deal with again.
